version: '4.15.0'
services:
  mongodb:
    image: "mongo"
    volumes:
      - data:/data/bd
  backend:
    build: ./back
    ports:
      - "4000:4000"
    volumes:
      - logs:/app/logs
      - ./backend:/app
      - /app/node_modules
    depends_on:
      - mongodb
  frontend:
    build: ./front
    ports:
    - "3000:3000"
    volumes:
    - ./frontend/src:/app/src
    stdin_open: true
    tty: true
    depends_on:
      - backend
volumes:
  data:
  logs:
